### ISSUE TITLE
Issue with "لأ" not showing in Arabic language in react-native-rtl-reshaper v1.0.2

### ISSUE THREAD

**Issue by faizanali1192** [h-assefi/React-Native-Rtl-Reshaper#1]
### Description:
I have encountered an issue while using the react-native-rtl-reshaper library version 1.0.2 in an Arabic language application. The word "لأ" was not being displayed properly. After investigating the issue, I found that some lines of code were commented out in the combCharsMap section of the library.

### **Before**

`combCharsMap = [
  //  [ [ 0x0644, 0x0622 ], 0xFEF5, null, null, 0xFEF6 ], /* LAM_ALEF_MADDA */
  //  [ [ 0x0644, 0x0623 ], 0xFEF7, null, null, 0xFEF8 ], /* LAM_ALEF_HAMZA_ABOVE */
  //  [ [ 0x0644, 0x0625 ], 0xFEF9, null, null, 0xFEFA ], /* LAM_ALEF_HAMZA_BELOW */
    [[0x0644, 0x0627], 0xfefb, null, null, 0xfefc] /* LAM_ALEF */,
],
`
After making the necessary changes to the code and uncommenting the above-mentioned lines, the issue was resolved.

### After
`combCharsMap = [
    [ [ 0x0644, 0x0622 ], 0xFEF5, null, null, 0xFEF6 ], /* LAM_ALEF_MADDA */
    [ [ 0x0644, 0x0623 ], 0xFEF7, null, null, 0xFEF8 ], /* LAM_ALEF_HAMZA_ABOVE */
    [ [ 0x0644, 0x0625 ], 0xFEF9, null, null, 0xFEFA ], /* LAM_ALEF_HAMZA_BELOW */
    [[0x0644, 0x0627], 0xfefb, null, null, 0xfefc] /* LAM_ALEF */,
],
`

I suggest that the library maintainers update the code in the next release to prevent this issue from occurring in the future.

**Comment by h-assefi** [comment]
Thank you for reporting the issue @faizanali1192 
bug resolved in version 1.0.3
